---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.295.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: dominikh/go-tools/staticcheck@2023.1.7
- name: goreleaser/goreleaser@v2.5.1
- name: securego/gosec@v2.22.0
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.10.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.6
- name: rust-lang/mdBook@v0.4.43
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.58.1
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.1.1
- name: oven-sh/bun@bun-v1.1.43
- name: k1LoW/octocov@v0.62.4
- name: google/yamlfmt@v0.14.0
- name: suzuki-shunsuke/ghalint@v1.2.1
- name: suzuki-shunsuke/pinact@v1.1.2
