# https://rust-lang.github.io/mdBook/

[book]
title = "dogowner"
description = "CLI wrapper tool with presets for commonly used Reviewdog settings"
authors = ["Takumi Takahashi"]
src = "docs"
language = "ja"
multilingual = false

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/takumin/dogowner"
