---
# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    deps:
    - gogen

  gogen:
    run: once
    sources:
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'
    - exclude: '**/*_test.go'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - go generate ./...
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
